on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: Test build

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      # Step that caches and restores maven dependencies
      - name: Cache maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install Dependencies
        run: sudo apt-get install -y genisoimage
      - name: Build with Maven
        run: mvn -B install --file pom.xml
