on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      # Step that caches and restores maven dependencies
      - name: Cache maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install Dependencies
        run: sudo apt-get install -y genisoimage
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Get Maven version
        run: echo "::set-env name=VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref }}
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            server/target/server-${{ env.VERSION }}.jar
            editor/target/editor-${{ env.VERSION }}.jar
            client/target/client-${{ env.VERSION }}.jar
            client/target/client-${{ env.VERSION }}.exe
            client/target/client-${{ env.VERSION }}.dmg
